# Generated by Django 5.1.1 on 2024-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0002_adminmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action_type',
            field=models.CharField(choices=[('BLOCK', 'Block Content'), ('UNBLOCK', 'Unblock Content'), ('DELETE', 'Delete Content'), ('WARN', 'Warn User')], max_length=100),
        ),
    ]
